### ISSUE TITLE
Scrollbar wonkiness when changing tabs

### ISSUE THREAD

**Issue by DirectorSCUD** [mutik/drmng#10]
Okay, so... I tend to scroll down the game window on my laptop a bit.
I start at the guild chat, as expected. When switching to alliance tab, the scroll extent gets bigger thoug, so the game "jumps" up and down when switching between guild and alliance chat frequently.
I hide most Kong frames, if that is important for the issue.

-Kendzi

**Comment by teclamat** [comment]
Let me know if still happens in v2.1.0

**Comment by teclamat** [comment]
Apparently it doesn't, closing
