### ISSUE TITLE
alliance chat scrolling

### ISSUE THREAD

**Issue by MarcoFedele** [mutik/drmng#2]
Right now, if I scroll up on the alliance chat (e.g. to read a 10-min-old conversation) but someone is writing in the meanwhile, I get scrolled down every time a new message appears :)

**Comment by teclamat** [comment]
### Proposed change
* add option named "Always scroll" with description "When enabled, chat will always scroll down with new content"
* by default option will be disabled

**Comment by Idrinth** [comment]
maybe only scroll down if the scroll bar is currently at the bottom?

**Comment by teclamat** [comment]
Might not work as expected when someone posts image link which gets formatted into `<img>` tag. Chat wont be at the very bottom that time and will stop scrolling even, when user haven't scrolled it up.

What about scrolling down when bottom of visible chat window is within last message area (even if not at very bottom)

**Comment by teclamat** [comment]
Scrolling behavior will be changed in version **2.0.25**

Expected behavior after change: _When you scroll up past last message area, chat wont auto scroll anymore._
