### ISSUE TITLE
Chat size issue

### ISSUE THREAD

**Issue by MarcoFedele** [mutik/drmng#6]
I'm reporting this for a friend of mine.

After he clicked on the "hide WC" button above the game (the one next to Reload Game and Reload Chat) the WC did disappeared, but kong guild one get quite large in size (he has alliance chat right next to guild one). At that point the "hide WC" button disappeared, and he could not resize guild chat (dragging the edge with the "double arrow" would not work). He tried to refresh game, reinstall script, but there's nothing he could to do manage to resize his abnormally large guild chat...!

I left on your wall the name of my friend ;)

**Comment by teclamat** [comment]
One time bug involving old option and introduced new one with same functionality. Shouldn't happen in the future.
