### ISSUE TITLE
Chat width changing randomly

### ISSUE THREAD

**Issue by rgreen83** [mutik/drmng#7]
This seems to happen most often when leaving the game window and coming back but the regular chat and alliance chat widths will randomly shrink, sometimes multiple times and it will just keep getting smaller and smaller, and must be dragged back out to the full screen width. This has multiple times nearly caused PC spending on bar refills because the chat would resize when returning to the game window after a bar was spent and the game then jerks to the side and causes you to click in a different place than intended.

**Comment by teclamat** [comment]
Fixed in 2.0.29
