### ISSUE TITLE
Alliance chat not scrolling to last message

### ISSUE THREAD

**Issue by rgreen83** [mutik/drmng#8]
Have to constantly drag the scroll bar down to view the latest alliance chat messages because it doesn't autoscroll and often reply to old messages. It doesn't scroll when posting a message either and will make you think it didn't post so you post the same message multiple times.

**Comment by teclamat** [comment]
I'd need more data on this issue. Asked few users and for them (and myself) alliance chat is scrolling as intended.

**Comment by rgreen83** [comment]
https://puu.sh/uPaPg/94c6a3a15c.png
Not sure what more info I can give that would be helpful. Im sure a picture wasn't required to understand not scrolling but its here anyways lol. I use chrome, stable branch. It's been happening since I first switched to the next gen script over a month ago. Is there some logging that could help that I can gather?

**Comment by teclamat** [comment]
Fixed in v 2.0.31
